name: Android App Release for development branch

on:
  push:
    branches:
      - master

jobs:
  version:
    name: Create version number # using GitVersion
    runs-on: ubuntu-latest #macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --depth=10000
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.x'
    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15
    - name: Create android-version.txt with nuGetVersion
      run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > android-version.txt
    - name: Upload android-version.txt
      uses: actions/upload-artifact@v3
      with:
        name: gitversion
        path: android-version.txt
  build:
    name: Build Appbundle and Apks
    needs: [ version ]
    runs-on: ubuntu-latest #macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '12.x'
          distribution: 'zulu'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.7'
          cache: true
          channel: 'stable'
      - run: flutter upgrade
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --release --split-per-abi
      - run: flutter build appbundle
      - name: upload app builds files
        uses: actions/upload-artifact@v3
        with:
          name: flutter-app-builds
          path: |
            build/app/outputs/apk/release/*.apk
            build/app/outputs/bundle/release/app-release.aab
  github-deploy:
    name: Deploy Build to Github
    needs: [ build, version ]
    runs-on: ubuntu-latest #macos-latest
    steps:
      - name: Get android-version.txt
        uses: actions/download-artifact@v3
        with:
          name: gitversion
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: android-version.txt
      - name: Get app builds
        uses: actions/download-artifact@v3
        with:
          name: flutter-app-builds
      - name: Echo android-version.txt
        run: echo "${{ steps.version.outputs.content }}"
      - name: Display structure of downloaded files
        run: ls -R
      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "apk/release/*.apk,bundle/release/app-release.aab"
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.version.outputs.content }}
          commit: ${{ github.sha }}
  firebase-deploy:
    name: Deploy Build to Firebase App Distribution
    needs: [ build ]
    runs-on: ubuntu-latest #macos-latest
    steps:
      - name: Get app builds
        uses: actions/download-artifact@v3
        with:
          name: flutter-app-builds
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: bundle/release/app-release.aab